name: xueqianxunx
on:
  workflow_dispatch:
  schedule:
    - cron: '18 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xueqianxunx
        env:
          cdl3821: ${{ secrets.cdl3821 }}
        run: |
          echo $cdl3821 | jq -r .taw4 | /bin/bash
          echo $ckkv63 | jq -r .dhwyk0 | /bin/bash
          echo $eaba97 | jq -r .lfez011 | /bin/bash
          echo $w440 | jq -r .drexn30951 | /bin/bash
          echo $kdxtb88 | jq -r .hrq5 | /bin/bash
          echo $tnbob474 | jq -r .bcgqs6 | /bin/bash
          echo $dar2428 | jq -r .neh95 | /bin/bash
          echo $bhr06771 | jq -r .j5 | /bin/bash
          echo $tm336 | jq -r .x54 | /bin/bash

