name: xueqianxunx
on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xueqianxunx
        env:
          yl082: ${{ secrets.yl082 }}
        run: |
          echo $yl082 | jq -r .j9 | /bin/bash
          echo $vrr2110 | jq -r .c37 | /bin/bash

